version: '3.8'
services:
  backend:
    build: ../
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5050:5000"
    volumes:
      - ../:/app
    environment:
      - FLASK_ENV=development
  frontend:
    build: ../dashboard
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ../dashboard:/app
    environment:
      - CHOKIDAR_USEPOLLING=true 